#################################
# Backend & sync
#################################
backend = "glx";
vsync = true;


#################################
# Rounded corners
#################################
corner-radius = 14;

rounded-corners = true;
rounded-corners-exclude = [
  "class_g != 'scratch-terminal' && class_g != 'Spotify'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];


#################################
# Opacity — leve transparência global + um pouco mais no editor
#################################
inactive-opacity = 0.93;
active-opacity = 0.97;

opacity-rule = [
  # Terminal scratch
  "88:class_g = 'scratch-terminal'",

  # Spotify scratch
  "88:class_g = 'Spotify'",

  # VS Code / forks — “transparentezinho” (~87% opaco)
  "87:class_g = 'Code'",
  "87:class_g = 'Cursor'",
  "87:class_g = 'VSCodium'"
];


#################################
# Blur suave (comentar estas 4 linhas se o teu picom der erro ao iniciar)
#################################
blur-method = "dual_kawase";
blur-strength = 5;
blur-background = true;

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];
