# Additional autostart programs (executed after keybindings)

# Brazilian keyboard layout
exec --no-startup-id setxkbmap br

# Monitor configuration handled by monitor.sh

# Polybar
exec_always --no-startup-id ~/.config/polybar/launch.sh

# Terminal scratchpad
exec --no-startup-id kitty --class "scratch-terminal"

# Spotify
exec --no-startup-id spotify

# Monitor setup
exec_always --no-startup-id ~/.config/i3/scripts/monitor.sh

# Wallpaper (load from Polybar state after monitor layout is applied)
exec_always --no-startup-id ~/.config/i3/scripts/load_wallpaper.sh

# Never turn off the monitors
exec --no-startup-id xset s off
exec --no-startup-id xset s noblank
exec --no-startup-id xset -dpms
